### ISSUE TITLE
Previously added graph breaks when adding an additional function to track/inspect?

### ISSUE THREAD

**Issue by larshei** [LivewareProblems/Orion#13] opened 2023-03-17 08:16 UTC
Thanks a lot, Orion is super awesome!

I was just playing around a bit and inspected some functions on my locally running dev setup.

As shown on the following screenshots, the second graph changes once the top graph is started.
It seems to "miss" function calls?
Every additional graph added from here on breaks the previously addd graph.
This effect occurs from adding the third graph, having just two graphs works as expected.

The behaviour was similar when running the inspected application (1) alone or (2) in a cluster with other applications.

Elixir Version is 1.14.3-otp-25

Please see this as a purely informative issue, for me personally I can just add less functions at once :) 

In case you would like more information, let me know what that would be.

|||
|--|--|
| ![image](https://user-images.githubusercontent.com/22884787/225846515-34413348-794a-4e81-80c2-789d210e9a71.png) | ![image](https://user-images.githubusercontent.com/22884787/225846572-d7964514-ce4e-45af-a180-8f5d2079dd78.png) |

**Comment by DianaOlympos** [comment] 2023-04-02 18:08
damnit I thought I had fixed this one. It is a recurring one that I cannot find the source of.  I will not have time to look at it soon, but I will have a look. No idea where to start the search though. They have different ids and all...

Also thanks for the report, it seems for strange reasons I was not watching the repo, so I was not getting alerted that issues were open. I should be more reactive now.

**Comment by DianaOlympos** [comment] 2023-04-10 16:38
Ok, the good news is that I managed to reproduce @larsh and worse. the problem is that I have no idea why. But eh now I can work on it.

**Comment by DianaOlympos** [comment] 2023-04-29 09:58
Ok i finally understand what is happening. This is going to be painful but not too hard to fix. Should have a release by end of weekend.

**Comment by DianaOlympos** [comment] 2023-04-29 17:41
@larshei Should be fixed in 1.0.3. This ended up being far nastier than expected.
Feel free to reopen if you see it happening again.

**Closed by DianaOlympos** 2023-04-29 17:41 UTC
Labels: bug
